const pillcolors = ["orange", "green", "blue", "red", "yellow", "purple"];

export const level1 = [
  [pillcolors[2], pillcolors[1], pillcolors[0]],
  [pillcolors[0], pillcolors[1], pillcolors[0], pillcolors[2]],
  [pillcolors[1], pillcolors[2], pillcolors[0], pillcolors[2]],
  [pillcolors[0], pillcolors[1], pillcolors[2], pillcolors[1]],
  [pillcolors[2], pillcolors[0], pillcolors[1]],
];

export const level2 = [
  [pillcolors[2], pillcolors[1], pillcolors[0], pillcolors[2], pillcolors[0]],
  [pillcolors[0], pillcolors[1], pillcolors[0], pillcolors[2], pillcolors[1]],
  [
    pillcolors[1],
    pillcolors[2],
    pillcolors[0],
    pillcolors[2],
    pillcolors[2],
    pillcolors[1],
  ],
  [pillcolors[0], pillcolors[1], pillcolors[1], pillcolors[0], pillcolors[2]],
  [
    pillcolors[2],
    pillcolors[0],
    pillcolors[1],
    pillcolors[2],
    pillcolors[0],
    pillcolors[1],
  ],
];

export const level3 = [
  [
    pillcolors[2],
    pillcolors[1],
    pillcolors[0],
    pillcolors[3],
    pillcolors[2],
    pillcolors[0],
  ],
  [pillcolors[0], pillcolors[1], pillcolors[0], pillcolors[2], pillcolors[1]],
  [
    pillcolors[1],
    pillcolors[2],
    pillcolors[0],
    pillcolors[2],
    pillcolors[2],
    pillcolors[2],
    pillcolors[3],
    pillcolors[1],
  ],
  [
    pillcolors[0],
    pillcolors[1],
    pillcolors[2],
    pillcolors[1],
    pillcolors[2],
    pillcolors[0],
    pillcolors[3],
    pillcolors[2],
  ],
  [
    pillcolors[2],
    pillcolors[0],
    pillcolors[1],
    pillcolors[2],
    pillcolors[0],
    pillcolors[1],
  ],
];

export const level4 = [
  [
    pillcolors[2],
    pillcolors[1],
    pillcolors[0],
    pillcolors[3],
    pillcolors[2],
    pillcolors[0],
  ],
  [
    pillcolors[0],
    pillcolors[1],
    pillcolors[0],
    pillcolors[2],
    pillcolors[1],
    pillcolors[3],
  ],
  [
    pillcolors[1],
    pillcolors[2],
    pillcolors[4],
    pillcolors[0],
    pillcolors[2],
    pillcolors[3],
    pillcolors[2],
    pillcolors[2],
    pillcolors[3],
    pillcolors[1],
  ],
  [
    pillcolors[0],
    pillcolors[1],
    pillcolors[2],
    pillcolors[1],
    pillcolors[2],
    pillcolors[0],
    pillcolors[4],
    pillcolors[3],
    pillcolors[2],
  ],
  [
    pillcolors[4],
    pillcolors[2],
    pillcolors[0],
    pillcolors[1],
    pillcolors[2],
    pillcolors[0],
    pillcolors[1],
    pillcolors[3],
  ],
];

export const level5 = [
  [
    pillcolors[2],
    pillcolors[1],
    pillcolors[0],
    pillcolors[3],
    pillcolors[2],
    pillcolors[0],
    pillcolors[5],
  ],
  [
    pillcolors[0],
    pillcolors[1],
    pillcolors[0],
    pillcolors[2],
    pillcolors[1],
    pillcolors[5],
    pillcolors[3],
    pillcolors[1],
  ],
  [
    pillcolors[1],
    pillcolors[2],
    pillcolors[4],
    pillcolors[0],
    pillcolors[2],
    pillcolors[3],
    pillcolors[5],
    pillcolors[2],
    pillcolors[2],
    pillcolors[3],
  ],
  [
    pillcolors[2],
    pillcolors[0],
    pillcolors[4],
    pillcolors[0],
    pillcolors[5],
    pillcolors[1],
    pillcolors[3],
    pillcolors[1],
    pillcolors[2],
    pillcolors[2],
  ],
  [
    pillcolors[2],
    pillcolors[0],
    pillcolors[5],
    pillcolors[1],
    pillcolors[5],
    pillcolors[4],
    pillcolors[1],
    pillcolors[3],
    pillcolors[2],
    pillcolors[0],
  ],
];
